---
name: devicemapper CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CHANGES.txt'
      - '**/README.md'

  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          - components: rustfmt
            task: make -f Makefile fmt-ci
          - components: clippy
            task: make -f Makefile clippy
          - components: cargo
            task: make -f Makefile build
          - components: cargo
            task: make -f Makefile docs
          - components: cargo
            task: make -f Makefile check-typos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: ${{ matrix.components }}
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: typos-cli
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Test ${{ matrix.task }} on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: ${{ matrix.task }}

  tests-with-sudo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Run all tests on CURRENT DEVELOPMENT RUST TOOLCHAIN
        run: sudo PATH=$GITHUB_WORKSPACE/.cargo/bin:$PATH make -f Makefile sudo_test
      - name: Install toml-cli
        run: pip install --user toml-cli
      - name: Get package MSRV
        id: msrv
        run: |
          PATH=${PATH}:/github/home/.local/bin MSRV=$(toml get --toml-path Cargo.toml "package.rust-version")
          echo "MSRV=$MSRV" >> "$GITHUB_OUTPUT"
      - name: Set toolchain override with sudo
        run: sudo /home/runner/.cargo/bin/rustup override set ${{ steps.msrv.outputs.MSRV }}
      - name: Run all tests on LOWEST SUPPORTED RUST TOOLCHAIN
        run: sudo PATH=$GITHUB_WORKSPACE/.cargo/bin:$PATH make -f Makefile sudo_test

  # VERIFICATION OF TEST INFRASTRUCTURE
  yamllint:
    runs-on: ubuntu-22.04
    container:
      image: fedora:43  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install dependencies for Fedora
        run: dnf install -y make yamllint
      - name: Run yamllint
        run: make -f Makefile yamllint
