---
name: devicemapper nightly

on:
  schedule:
    - cron: 0 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
      - name: Audit check
        run: make -f Makefile audit

  checks-with-ci-repo:
    runs-on: ubuntu-22.04
    container:
      image: fedora:43  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - name: Install git for checkout action
        run: dnf install -y git
      - uses: actions/checkout@v6
        with:
          path: devicemapper-rs
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: cargo
          rust-src-dir: devicemapper-rs
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          make
          openssl-devel
          python-requests
          python-semantic_version
      - name: Check out ci repo
        uses: actions/checkout@v6
        with:
          path: ci
          repository: stratis-storage/ci
          persist-credentials: false
      - name: Run comparison of version specs with -sys package
        run: |
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=rawhide make -f ../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f44 make -f ../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f43 make -f ../Makefile check-fedora-versions
        working-directory: devicemapper-rs/devicemapper-rs-sys
      - name: Run comparison of version specs with package
        run: |
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=rawhide make -f Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f44 make -f Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=$GITHUB_WORKSPACE/ci/dependency_management/compare_fedora_versions FEDORA_RELEASE=f43 make -f Makefile check-fedora-versions
        working-directory: devicemapper-rs

  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Do semantic version checks on devicemapper-rs-sys
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
          manifest-path: devicemapper-rs-sys
      - name: Do semantic version checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
